package com.powergen.customerservice.webservice.registration;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-22T10:11:40.055-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://serviceplandetails.webservices.utilityservices.powergen.com/", name = "ServicePlanWS")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicePlanWS {

    @WebMethod
    @RequestWrapper(localName = "getServicePlans", targetNamespace = "http://serviceplandetails.webservices.utilityservices.powergen.com/", className = "com.powergen.customerservice.webservice.registration.GetServicePlans")
    @ResponseWrapper(localName = "getServicePlansResponse", targetNamespace = "http://serviceplandetails.webservices.utilityservices.powergen.com/", className = "com.powergen.customerservice.webservice.registration.GetServicePlansResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.powergen.customerservice.webservice.registration.ServicePlan> getServicePlans();
}
