
package com.powergen.customerservice.webservice.registration;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-22T10:11:39.998-05:00
 * Generated source version: 3.1.7
 * 
 */
public final class ServicePlanWS_ServicePlanWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://serviceplandetails.webservices.utilityservices.powergen.com/", "ServicePlanWSService");

    private ServicePlanWS_ServicePlanWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicePlanWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServicePlanWSService ss = new ServicePlanWSService(wsdlURL, SERVICE_NAME);
        ServicePlanWS port = ss.getServicePlanWSPort();  
        
        {
        System.out.println("Invoking getServicePlans...");
        java.util.List<com.powergen.customerservice.webservice.registration.ServicePlan> _getServicePlans__return = port.getServicePlans();
        System.out.println("getServicePlans.result=" + _getServicePlans__return);


        }

        System.exit(0);
    }

}
