package com.powergen.customerservice.webservice.registration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-19T02:36:21.714-05:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "ServicePlanWSService", 
                  wsdlLocation = "file:/C:/BCJMay16/Development/PowerGenCustomerService/PGCustomerRegistration/src/main/resources/netsuite.wsdl",
                  targetNamespace = "http://serviceplandetails.webservices.utilityservices.powergen.com/") 
public class ServicePlanWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://serviceplandetails.webservices.utilityservices.powergen.com/", "ServicePlanWSService");
    public final static QName ServicePlanWSPort = new QName("http://serviceplandetails.webservices.utilityservices.powergen.com/", "ServicePlanWSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/BCJMay16/Development/PowerGenCustomerService/PGCustomerRegistration/src/main/resources/netsuite.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicePlanWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/BCJMay16/Development/PowerGenCustomerService/PGCustomerRegistration/src/main/resources/netsuite.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicePlanWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicePlanWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicePlanWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ServicePlanWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServicePlanWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServicePlanWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ServicePlanWS
     */
    @WebEndpoint(name = "ServicePlanWSPort")
    public ServicePlanWS getServicePlanWSPort() {
        return super.getPort(ServicePlanWSPort, ServicePlanWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePlanWS
     */
    @WebEndpoint(name = "ServicePlanWSPort")
    public ServicePlanWS getServicePlanWSPort(WebServiceFeature... features) {
        return super.getPort(ServicePlanWSPort, ServicePlanWS.class, features);
    }

}
